# Generated by Django 4.2.7 on 2024-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.TextField()),
                ("password_hash", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("S", "Student"), ("C", "Co-Ordinator")], max_length=1
                    ),
                ),
                ("approved", models.BooleanField()),
            ],
        ),
    ]
