version: '3'
services:
  pgsql:  # changed from 'database' to 'pgsql'
    image: postgres:16.1-alpine
    container_name: pgsql
    restart: always
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=default_user
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=application

  app:
    build: .
    ports:
      - 8000:80
